// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-Zccq1bggXyrUw3bhMB3EZJLVFaQDvMQ',
    appId: '1:916515634197:android:951959e59f18e51e46e21c',
    messagingSenderId: '916515634197',
    projectId: 'trying-179504',
    databaseURL: 'https://trying-179504.firebaseio.com',
    storageBucket: 'trying-179504.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4MEMgPe7I1QQJI4LT0Cie5oJloURROxY',
    appId: '1:916515634197:ios:62a5ae5e5aee153546e21c',
    messagingSenderId: '916515634197',
    projectId: 'trying-179504',
    databaseURL: 'https://trying-179504.firebaseio.com',
    storageBucket: 'trying-179504.firebasestorage.app',
    androidClientId: '916515634197-6vqcb1j59kd5c7pr82jssgqs1ac1fug4.apps.googleusercontent.com',
    iosClientId: '916515634197-tqp0dkfc1hlpah79rnra76qi0k0abtno.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
